### ISSUE TITLE
Add ability to load "children of children" in a Field using FromLoader

### ISSUE THREAD

**Issue by IuriiKrasnov** [epam/epam-graphql#49]
### Description

I have such DB entities configuration:
**Parent** which has children of type **Child** which in its turn has children of type **ChildOfChild**. 
I need to load items of type **ChildOfChild** directly for **Parent**:
parent {
  childrenOfChildren {
    items {...}
  }
}
having ability to provide Filter and Search params for items of childrenOfChildren.

### Describe the solution you'd like

```
Field("childrenOfChildren").FromLoader<ChildOfChildLoader, ChildOfChild>((parent, childOfChild) => parent.Id == childOfChild.Parent.ParentId)
   .AsConnection()
   .WithFilter<ChildOfChildLoaderFilter>()
   .WithSearch<ChildOfChildSearcher<ChildOfChild>>();
```

**Comment by kuzn-ilya** [comment]
@IuriiKrasnov, I am closing this issue because it is not reproducible (v2.3.0), your example works fine. Fill free to reopen it with exact steps.

**Comment by IuriiKrasnov** [comment]
@kuzn-ilya, I can confirm the desired solution for this case works in new version. Thank you!
